import { AIHotspotResponse, AIInsightsResponse, AIRiskResponse, ChangeResponse, LULCAnalyticsResponse } from "@/types/api";

export interface ReportData {
  city: string;
  cityName: string;
  year: number;
  startYear: number;
  endYear: number;
  analytics: LULCAnalyticsResponse;
  change: ChangeResponse;
  risk?: AIRiskResponse;
  hotspots?: AIHotspotResponse;
  insights?: AIInsightsResponse;
  simulation?: {
    targetYear: number;
    scenario: string;
    result: any;
  };
}

export function generateDetailedReport(data: ReportData): string {
  const { cityName, year, startYear, endYear, analytics, change, risk, hotspots, insights, simulation } = data;

  let report = `# AI Urban Intelligence Report: ${cityName}\n\n`;
  report += `**Reporting Period:** ${startYear} - ${endYear}\n`;
  report += `**Target Analysis Year:** ${year}\n`;
  report += `**Generated on:** ${new Date().toLocaleString()}\n\n`;

  report += `## 1. Executive Summary\n`;
  report += `This report provides a comprehensive overview of urban growth and land-use dynamics in ${cityName}. `;
  report += `Using advanced satellite imagery analysis and AI-driven spatial models, we have assessed the transformation of the urban landscape from ${startYear} to ${endYear}.\n\n`;

  report += `## 2. Land Use / Land Cover (LULC) Distribution (${year})\n`;
  report += `The current distribution of land cover in ${cityName} for the year ${year} is as follows:\n\n`;
  
  const dist = analytics.distribution;
  report += `- **Forest:** ${(dist.forest * 100).toFixed(1)}%\n`;
  report += `- **Water Bodies:** ${(dist.water * 100).toFixed(1)}%\n`;
  report += `- **Agriculture:** ${(dist.agriculture * 100).toFixed(1)}%\n`;
  report += `- **Barren Land:** ${(dist.barren * 100).toFixed(1)}%\n`;
  report += `- **Built-up (Urban):** ${(dist.builtup * 100).toFixed(1)}%\n\n`;

  report += `## 3. Urban Transition Analysis (${startYear} - ${endYear})\n`;
  report += `Over the last ${endYear - startYear} years, the city has undergone significant spatial restructuring. `;
  
  // Find the top transition
  let maxTransition = { from: "", to: "", value: 0 };
  const matrix = analytics.transition_matrix;
  const classes = ["Forest", "Water Bodies", "Agriculture", "Barren Land", "Built-up"];
  
  matrix.forEach((row, i) => {
    row.forEach((val, j) => {
      if (i !== j && val > maxTransition.value) {
        maxTransition = { from: classes[i], to: classes[j], value: val };
      }
    });
  });

  if (maxTransition.value > 0) {
    report += `The most significant land cover transition observed was from **${maxTransition.from}** to **${maxTransition.to}**, accounting for **${(maxTransition.value * 100).toFixed(1)}%** of the targeted area change.\n\n`;
  }

  if (risk && risk.alerts.length > 0) {
    report += `## 4. AI Risk Assessment\n`;
    report += `Our AI-driven risk models have identified several critical areas of concern:\n\n`;
    risk.alerts.forEach((alert) => {
      report += `- ⚠️ **Alert:** ${alert}\n`;
    });
    report += `\n`;
  }

  if (hotspots) {
    report += `## 5. Hotspot Analysis\n`;
    report += `Spatial clustering analysis detected **${hotspots.statistics.high_pixels.toLocaleString()}** high-intensity change pixels. `;
    report += `These regions indicate accelerated urban footprint expansion and potential loss of permeable surfaces.\n\n`;
  }

  if (insights && insights.recommendations.length > 0) {
    report += `## 6. AI Strategic Recommendations\n`;
    report += `Based on the observed trends and risk factors, the following policy interventions are recommended:\n\n`;
    insights.recommendations.forEach((rec, i) => {
      report += `${i + 1}. **${rec}**\n`;
    });
    report += `\n`;
  }

  if (simulation) {
    report += `## 7. Future Growth Simulation (${simulation.targetYear})\n`;
    report += `Projected growth for the year **${simulation.targetYear}** under the **"${simulation.scenario}"** scenario suggests a continuing trend of urban consolidation. `;
    report += `Early intervention in green-zone protection is advised to mitigate heat-island effects.\n\n`;
  }

  report += `---\n*Generated by SolarScan AI Intelligence Platform*`;

  return report;
}
